name: myfirstworkflow
on: [push]
jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: My first step
        run: echo "Hello, World!"

      - name: List files
        run: ls -la

      - name: Read a file
        run: cat README.md              
        




